name: publish to github pages

on:
  push:
    branches:
      - master
jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        uses: actions/setup-node@v3
        with:
          node-version: '15.x'
          cache: npm
      - name: npm update
        if: ${{ steps.setup_node_id.outputs.cache-hit != 'true' }}
        run: npm install
      - name: Cache public
        uses: actions/cache@v3
        id: public
        with:
          path: public
          key: ${{ runner.OS }}-public-${{ github.sha }}
          restore-keys: |
            ${{ runner.OS }}-public-
      - name: Cache db.json
        uses: actions/cache@v3
        id: db
        with:
          path: db
          key: ${{ runner.OS }}-db-${{ github.sha }}
          restore-keys: |
            ${{ runner.OS }}-db-
      - name: prepare db
        run: |
          if [ -e db/db.json ]; then
            cp db/db.json ./
          fi
      - name: npm build
        run: npm run build
        env:
          TZ: Asia/Tokyo
      - name: update db
        run: |
          mkdir -p db
          cp -f ./db.json db/
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTION_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./public