name: publish to github pages

on:
  push:
    branches:
      - master
jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: build
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Cache node modules
        uses: actions/cache@v1
        id: cache_node_modules
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-
      - name: Cache public
        uses: actions/cache@v1
        id: public
        with:
          path: public
          key: ${{ runner.OS }}-public-${{ github.sha }}
          restore-keys: |
            ${{ runner.OS }}-public-
      - name: Cache db.json
        uses: actions/cache@v1
        id: db
        with:
          path: db.json
          key: ${{ runner.OS }}-db-${{ github.sha }}
          restore-keys: |
            ${{ runner.OS }}-db-
      - name: Install
        if: steps.cache_node_modules.cache-hit != 'true'
        run: npm install
      - name: Build
        run: npm run build
        env:
          TZ: Asia/Tokyo
      - name: deploy
        uses: peaceiris/actions-gh-pages@v2.4.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTION_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./public
